db:
  url: jdbc:postgresql://ec2-54-75-231-3.eu-west-1.compute.amazonaws.com:5432/d8tmsdtk552drk
  username: xmsrvmorkijeiq
  password: f119a43ffb41c3663fca000769d41966178d6052fcbd55fb4a185368afada2d3

dbcp:
  maxTotal: 4
  testOnBorrow: true
  validationQuery: SELECT 1

web:
  sessionAge: 3600